<a href="https://colab.research.google.com/github/AnerGcorp/machine_learning_examples/blob/master/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7, 7)
x

tensor([[0.5309, 0.7525, 0.7614, 0.0939, 0.3817, 0.1260, 0.3608],
        [0.4116, 0.2731, 0.4832, 0.1410, 0.7477, 0.8348, 0.0866],
        [0.8672, 0.9952, 0.2744, 0.5472, 0.8619, 0.0483, 0.5286],
        [0.4711, 0.8254, 0.7301, 0.5611, 0.4238, 0.7715, 0.1013],
        [0.3115, 0.3037, 0.0100, 0.5923, 0.5522, 0.5807, 0.0289],
        [0.8944, 0.8030, 0.9264, 0.3330, 0.4900, 0.3640, 0.0837],
        [0.0460, 0.0136, 0.9338, 0.2648, 0.3971, 0.3274, 0.0127]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
y = torch.rand(1, 7)
# Perform matrix multiplication
z = torch.matmul(x, y.T)
z

tensor([[1.5501],
        [1.1817],
        [2.0319],
        [1.6604],
        [0.8703],
        [2.0888],
        [0.8993]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
random_tensor_C = torch.matmul(random_tensor_A, random_tensor_B.T)
random_tensor_C

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [3]:
import torch

# Set random seed
RANDOM_SEED = 1234


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(size=(2, 3)).to(device)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(size=(2, 3)).to(device)
print(f"Device: {device}")
random_tensor_A, random_tensor_B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(random_tensor_A, random_tensor_B.T)
output, output.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max_value = output.max()
# Find min
min_value = output.min()

max_value, min_value

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
argmax_value = output.argmax()

# Find arg min
argmin_value = output.argmin()

argmax_value, argmin_value

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))